### ISSUE TITLE
Faire point ave Thib et Ana des listes d'amélioration possible du site

### ISSUE THREAD

**Issue by Matthieu69007** [Matthieu69007/TrackerWorld#10]

**Comment by thibaultgrad** [comment]
- [x] Sur home => inverser la map monde et la timeline pour mieux comprendre le projet
- [x] Sur cette page mettre le bouton règles en détail sous la timeline plutot qu'au dessus
- [x] Ajouter un titre à la timeline
- [x] Mettre la timeline en premier sur la page en fait

**Comment by thibaultgrad** [comment]
- [ ] SUpprimer la timeline dans les regles qui me parait être une redite

La navigation du site c'est home puis on lit la timeline etc puis on va vers les regles en détails via le lien. Je serais presque d'avis d'enlever le lien dans le header vers Presentation

**Comment by Matthieu69007** [comment]
Je suis d'accord avec le fait d'enlever la timeline de la partie regle, et d'enlever lee lien vers présentation. Par contre je trouverai ça bien de réfléchir à une logique pour qu'en cliquant de lien en lien, on puisse finir par lire toutes les pages. Parce que j'ai peur que la on saute sur les règles, mais qu'on ne lise jamais la présentation. A creuserr, j'y réfléchirai

**Comment by thibaultgrad** [comment]
Agree
