### ISSUE TITLE
Acheter domaine Traceacrossthewold.com (Matthieu)

### ISSUE THREAD

**Issue by Matthieu69007** [Matthieu69007/TrackerWorld#15]
Puis migrer le site dessus

**Comment by sbsrouteur** [comment]
Je ne sais pas s'ils vendent du .com, mais free vend à pas cher, j'ai acheté 30€ mon .fr pour 5ans
bookmyname.com

**Comment by Matthieu69007** [comment]
https://docs.github.com/fr/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site
