### ISSUE TITLE
Bug affichage des images si on change la langue alors que l'on est déjà dans la page itinéraire

### ISSUE THREAD

**Issue by Matthieu69007** [Matthieu69007/TrackerWorld#17]
Si on choisit la langue puis que l'on va sur la page, cela fonctionne correctement (dans les deux langues), mais si une fois sur la page itinéraire on change de langue, alors les images ne s'affichent plus

**Comment by sbsrouteur** [comment]
closed with b73ae9bbf728e5cd367c2298ab99e027ce8bd924
