### ISSUE TITLE
changer les noms de fichiers qui ont des accents

### ISSUE THREAD

**Issue by sbsrouteur** [Matthieu69007/TrackerWorld#2]
Ils ne passent pas à la traduction crowdin.

Ca concerne au moins les noms de villes dans le parcours Götheborg... et la référence dans le fichier des villes

**Comment by Matthieu69007** [comment]
Faire deux colonnes dans le drive, une avec les noms sans accents pour la recherche et les liens des fichiers, l'autre avec les accents qui sera le nom affiché

![image](https://github.com/Matthieu69007/TrackerWorld/assets/138585468/0c69e4b9-ce79-4e69-b3b6-a49760c4706e)

**Comment by Matthieu69007** [comment]
Close c07b2534aca2e7876181359d65804b43adaf1be3
