### ISSUE TITLE
Créer les langues de traduction dans le projet CrowdIn

### ISSUE THREAD

**Issue by Matthieu69007** [Matthieu69007/TrackerWorld#22]
- [ ] allemand
- [ ] espagnol
- [ ] portuguais
- [ ] hindi
- [ ] arabe
- [ ] mandarin
- [ ] tchèque
- [ ] hongrois
- [ ] polonais

**Comment by sbsrouteur** [comment]
done y a pu qu'à .....

Faudra decider à partir de quelle pourcentage de traduc on le met dans les langues sur le site
