### ISSUE TITLE
Comprendre problème de publication des langues (source notamment) qui ne s'affiche pas selon le docs/XXX

### ISSUE THREAD

**Issue by Matthieu69007** [Matthieu69007/TrackerWorld#26]
il y a un truc que je ne comprend pas à propose de la traduction. C'est d'où vient la version française qui est affichée sur le site. Sur la page ViePrivee, j'ai une ligne qui parle de la RGPD dans docs/ViePrivee.  Par contre, je n'ai pas cette ligne dans docs/i18n/fr/vieprivee (le texte est même en anglais). Et quand je vais sur le site (en local après mise à jour de mon repo), j'ai un texte qui s'affiche en français sans parler de la RGPD.

![image](https://github.com/Matthieu69007/TrackerWorld/assets/138585468/18262999-0fa4-43ef-ab25-f9929ee8d99f)

![image](https://github.com/Matthieu69007/TrackerWorld/assets/138585468/297554e3-bf1f-4511-b02c-3411fb087007)

**Comment by sbsrouteur** [comment]
Il faut travailler dans docs. J'ai reset tous les fichiers, et ça semble clean dans le repo et sur crowdin.
Je viens de publier sur le site et on a bien la note rgpd en fr et dans la tradcu anglaise
