### ISSUE TITLE
[Time Line] 

### ISSUE THREAD

**Issue by Matthieu69007** [Matthieu69007/TrackerWorld#30]
Changer la phrase pour la step 2 pour plus de compréhension :

Travel with Trace
To help Trace to get closer to the next step of its travel plan : CITY_NAME

<img width="298" alt="image" src="https://github.com/Matthieu69007/TrackerWorld/assets/138585468/5992af35-a333-4f7f-b364-121be68850e8">

**Comment by sbsrouteur** [comment]
Il faut mettre à jour le code react pour ça avnt de faire la traduc
