### ISSUE TITLE
Fixer position icone instagram et choix langue

### ISSUE THREAD

**Issue by Matthieu69007** [Matthieu69007/TrackerWorld#5]
S'arranger pour que l'icone changement de langue et Instagram restent toujours en haut à droite dans le bandeau principal, même en mode écran de téléphone

![image](https://github.com/Matthieu69007/TrackerWorld/assets/138585468/c6fb49f7-63f4-466f-a4c6-269d1fc248f7)

**Comment by sbsrouteur** [comment]
Bon on peut pas parce que c'est une seule navbar en fait:
![image](https://github.com/Matthieu69007/TrackerWorld/assets/11095871/86f22632-045a-459a-903d-65fee4364e27)

Cepedant on peut tout mettre à gauche, comme ça, tu est moins traumatisé quand ça passe en mode "small" et que tout disparait dans le menu sandwich.

Ptet que @Rufus31415 connais mieux docusaurus, mais la doc parle pas mal du layout, mais pas du tout du 'responsive' qui serait le sujet à creuser pour ça.

**Comment by Matthieu69007** [comment]
Plus d'actualité depuis qu'on a qu'une seule page
