### ISSUE TITLE
Bug bouton plein écran carte cesium

### ISSUE THREAD

**Issue by Matthieu69007** [Matthieu69007/TrackerWorld#8]
- [ ] Rendre le bouton plus gros
- [ ] Sur certains navigateur (firefox, safari), le bouton n'a aucun effet

![image](https://github.com/Matthieu69007/TrackerWorld/assets/138585468/4bfa536a-7e07-458f-a881-9d6f46cca5dc)

**Comment by sbsrouteur** [comment]
fixed in leaflet
